"""Deterministic migration-script generator (iter-13.44).

Produces the three Stage 2 Python scripts without any LLM call:
    1. migrate_old_to_oltp.py — legacy DB → PostgreSQL OLTP (2-pass id-map)
    2. migrate_oltp_to_olap.py — OLTP → star schema (ETL per dim, per fact)
    3. test_migration.py       — pytest row-count + FK + measure-sum checks

All three are templated. Per-project variability comes entirely from:
    • the kb_entities table list (drives source table iteration)
    • the OLTP entity definitions (drives target table iteration)
    • the bus_matrix (drives dim_/fact_ ETL loops)
"""
from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional


def _sanitise(name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", (name or "").lower()).strip("_") or "_unnamed"


# ----------------------------------------------------------------------------
# Script 1 — Legacy → OLTP
# ----------------------------------------------------------------------------
_OLD_TO_OLTP_TEMPLATE = '''"""migrate_old_to_oltp.py — generated by LAMA (iter-13.44, deterministic).

Migrates data from the legacy {source_tech} database to the new PostgreSQL
OLTP schema. Two-pass strategy:
    Pass 1 — INSERT every legacy row into the corresponding target table,
             generating a UUID PK and recording the id-mapping in a side
             table `_migration_id_map(table_name, legacy_id, new_id)`.
    Pass 2 — Re-walk the source, locate every FK column, look up the new
             UUID for the referenced row, and UPDATE the target FK column.

Env vars:
    SOURCE_DB_HOST, SOURCE_DB_PORT (default 3306),
    SOURCE_DB_USER, SOURCE_DB_PASSWORD, SOURCE_DB_NAME
    TARGET_DB_HOST, TARGET_DB_PORT (default 5432),
    TARGET_DB_USER, TARGET_DB_PASSWORD, TARGET_DB_NAME
"""
from __future__ import annotations

import os
import uuid
import logging
from typing import Any, Dict, List, Tuple

import psycopg2
import psycopg2.extras

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("migrate_old_to_oltp")

BATCH_SIZE = 1000

# (legacy_table, target_table, [(legacy_col, target_col, is_fk, fk_ref_table)])
TABLES: List[Tuple[str, str, List[Tuple[str, str, bool, str]]]] = {tables_literal}

# Reverse-lookup for FK rewiring in pass 2 — built lazily from TABLES.
def _fk_columns(tbl: str) -> List[Tuple[str, str, str]]:
    """Returns [(target_col, ref_table, legacy_col), ...] for one table."""
    out = []
    for legacy_table, target_table, cols in TABLES:
        if target_table != tbl:
            continue
        for legacy_col, target_col, is_fk, ref_table in cols:
            if is_fk and ref_table:
                out.append((target_col, ref_table, legacy_col))
    return out


def _connect_source():
    try:
        import pymysql
    except ImportError as e:
        raise SystemExit("PyMySQL required for source connection: pip install PyMySQL") from e
    return pymysql.connect(
        host=os.environ["SOURCE_DB_HOST"],
        port=int(os.environ.get("SOURCE_DB_PORT", "3306")),
        user=os.environ["SOURCE_DB_USER"],
        password=os.environ["SOURCE_DB_PASSWORD"],
        database=os.environ["SOURCE_DB_NAME"],
        cursorclass=pymysql.cursors.DictCursor,
        charset="utf8mb4",
    )


def _connect_target():
    return psycopg2.connect(
        host=os.environ["TARGET_DB_HOST"],
        port=int(os.environ.get("TARGET_DB_PORT", "5432")),
        user=os.environ["TARGET_DB_USER"],
        password=os.environ["TARGET_DB_PASSWORD"],
        dbname=os.environ["TARGET_DB_NAME"],
    )


def _ensure_id_map(tgt) -> None:
    with tgt.cursor() as cur:
        cur.execute(
            "CREATE TABLE IF NOT EXISTS _migration_id_map ("
            "table_name TEXT NOT NULL, "
            "legacy_id TEXT NOT NULL, "
            "new_id UUID NOT NULL, "
            "PRIMARY KEY (table_name, legacy_id))"
        )
        tgt.commit()


def _record_id_map(tgt, rows: List[Tuple[str, str, str]]) -> None:
    if not rows:
        return
    with tgt.cursor() as cur:
        psycopg2.extras.execute_values(
            cur,
            "INSERT INTO _migration_id_map (table_name, legacy_id, new_id) "
            "VALUES %s ON CONFLICT DO NOTHING",
            rows,
        )
    tgt.commit()


def _lookup_new_id(tgt, ref_table: str, legacy_id: Any) -> str | None:
    with tgt.cursor() as cur:
        cur.execute(
            "SELECT new_id FROM _migration_id_map WHERE table_name=%s AND legacy_id=%s",
            (ref_table, str(legacy_id)),
        )
        row = cur.fetchone()
        return str(row[0]) if row else None


def pass_one(src, tgt) -> None:
    """Insert every row + record id-mapping. FK columns are left NULL here
    and filled in pass 2."""
    for legacy_table, target_table, cols in TABLES:
        log.info("Pass-1 · %s → %s", legacy_table, target_table)
        with src.cursor() as scur:
            scur.execute(f"SELECT * FROM `{{legacy_table}}`")
            while True:
                rows = scur.fetchmany(BATCH_SIZE)
                if not rows:
                    break
                target_cols = ["id"] + [tc for _, tc, is_fk, _ in cols if not is_fk]
                placeholders = ", ".join(["%s"] * len(target_cols))
                col_csv = ", ".join(f'"{{c}}"' for c in target_cols)
                id_map_rows = []
                values = []
                for r in rows:
                    new_id = str(uuid.uuid4())
                    legacy_id = r.get("id") or r.get(f"{{legacy_table}}_id") or next(iter(r.values()))
                    id_map_rows.append((target_table, str(legacy_id), new_id))
                    row_vals = [new_id]
                    for legacy_col, _, is_fk, _ in cols:
                        if is_fk:
                            continue
                        row_vals.append(r.get(legacy_col))
                    values.append(tuple(row_vals))
                with tgt.cursor() as tcur:
                    psycopg2.extras.execute_batch(
                        tcur,
                        f'INSERT INTO "{{target_table}}" ({{col_csv}}) VALUES ({{placeholders}}) ON CONFLICT DO NOTHING',
                        values,
                    )
                tgt.commit()
                _record_id_map(tgt, id_map_rows)


def pass_two(src, tgt) -> None:
    """Rewire FK columns using the id-map populated by pass 1."""
    for legacy_table, target_table, cols in TABLES:
        fk_cols = _fk_columns(target_table)
        if not fk_cols:
            continue
        log.info("Pass-2 · %s FK rewire (%d cols)", target_table, len(fk_cols))
        with src.cursor() as scur:
            scur.execute(f"SELECT * FROM `{{legacy_table}}`")
            while True:
                rows = scur.fetchmany(BATCH_SIZE)
                if not rows:
                    break
                for r in rows:
                    legacy_id = r.get("id") or next(iter(r.values()))
                    new_id = _lookup_new_id(tgt, target_table, legacy_id)
                    if not new_id:
                        continue
                    set_clauses = []
                    params: List[Any] = []
                    for target_col, ref_table, legacy_col in fk_cols:
                        legacy_fk_val = r.get(legacy_col)
                        if legacy_fk_val is None:
                            continue
                        new_fk = _lookup_new_id(tgt, ref_table, legacy_fk_val)
                        if not new_fk:
                            continue
                        set_clauses.append(f'"{{target_col}}" = %s')
                        params.append(new_fk)
                    if not set_clauses:
                        continue
                    params.append(new_id)
                    with tgt.cursor() as tcur:
                        tcur.execute(
                            f'UPDATE "{{target_table}}" SET {{", ".join(set_clauses)}} WHERE "id" = %s',
                            params,
                        )
        tgt.commit()


def main() -> None:
    src = _connect_source()
    tgt = _connect_target()
    try:
        _ensure_id_map(tgt)
        pass_one(src, tgt)
        pass_two(src, tgt)
        log.info("Migration complete: %d tables", len(TABLES))
    finally:
        src.close()
        tgt.close()


if __name__ == "__main__":
    main()
'''


# ----------------------------------------------------------------------------
# Script 2 — OLTP → OLAP star
# ----------------------------------------------------------------------------
_OLTP_TO_OLAP_TEMPLATE = '''"""migrate_oltp_to_olap.py — generated by LAMA (iter-13.44, deterministic).

ETL from the OLTP schema into the OLAP star schema:
    • For each dimension → INSERT INTO dim_<x> SELECT <natural_key>, attrs FROM <source_oltp>.
    • For each fact      → INSERT INTO fact_<x> SELECT date_key, dim_keys, measures
                           FROM <source_oltp> joined to the relevant OLTP tables.
"""
from __future__ import annotations

import os
import logging
from datetime import date, timedelta

import psycopg2

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("migrate_oltp_to_olap")


def _connect():
    return psycopg2.connect(
        host=os.environ["TARGET_DB_HOST"],
        port=int(os.environ.get("TARGET_DB_PORT", "5432")),
        user=os.environ["TARGET_DB_USER"],
        password=os.environ["TARGET_DB_PASSWORD"],
        dbname=os.environ["TARGET_DB_NAME"],
    )


def populate_dim_date(conn) -> None:
    """Populate dim_date covering [today-3y, today+1y]."""
    start = date(date.today().year - 3, 1, 1)
    end = date(date.today().year + 1, 12, 31)
    log.info("Populating dim_date %s → %s", start, end)
    rows = []
    cur_date = start
    while cur_date <= end:
        rows.append((
            int(cur_date.strftime("%Y%m%d")),
            cur_date,
            cur_date.strftime("%A"),
            cur_date.day,
            int(cur_date.strftime("%W")) or 1,
            cur_date.month,
            cur_date.strftime("%B"),
            (cur_date.month - 1) // 3 + 1,
            cur_date.year,
            cur_date.weekday() >= 5,
            False,
            cur_date.year,
            (cur_date.month - 1) // 3 + 1,
        ))
        cur_date += timedelta(days=1)
    with conn.cursor() as c:
        c.executemany(
            "INSERT INTO dim_date (date_key, full_date, day_of_week, day_of_month, week_number, "
            "month_number, month_name, quarter, year, is_weekend, is_holiday, fiscal_year, fiscal_quarter) "
            "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) ON CONFLICT DO NOTHING",
            rows,
        )
    conn.commit()


# (dim_table, source_oltp_table, natural_key_col, [(attr_name, source_col), ...])
DIMENSIONS = {dims_literal}

# (fact_table, source_oltp_table, date_source_col, [(dim_key, ref_dim, ref_natural_col, source_join_col), ...], [(measure, source_col), ...])
FACTS = {facts_literal}


def load_dimensions(conn) -> None:
    for dim_table, src_table, natural_col, attrs in DIMENSIONS:
        log.info("Loading %s from %s", dim_table, src_table)
        attr_csv  = ", ".join(['"natural_key"'] + [f'"{{a}}"' for a, _ in attrs])
        select_csv = ", ".join([f'CAST("{{natural_col}}" AS VARCHAR)']
                               + [f'"{{sc}}"' for _, sc in attrs])
        with conn.cursor() as c:
            c.execute(
                f'INSERT INTO "{{dim_table}}" ({{attr_csv}}) '
                f'SELECT DISTINCT {{select_csv}} FROM "{{src_table}}" '
                f'ON CONFLICT DO NOTHING'
            )
        conn.commit()


def load_facts(conn) -> None:
    for fact_table, src_table, date_col, dim_joins, measures in FACTS:
        log.info("Loading %s from %s", fact_table, src_table)
        dim_select = ", ".join(
            f'(SELECT "{{ref_dim}}_key" FROM "{{ref_dim}}" '
            f"WHERE \\"natural_key\\" = CAST(s.\\"{{join_col}}\\" AS VARCHAR) "
            f"AND is_current = TRUE LIMIT 1) AS \\"{{dim_key}}\\""
            for dim_key, ref_dim, _ref_nat, join_col in dim_joins
        )
        m_csv = ", ".join(f's."{{sc}}" AS "{{mn}}"' for mn, sc in measures)
        dim_cols = ", ".join(f'"{{dk}}"' for dk, *_ in dim_joins)
        meas_cols = ", ".join(f'"{{mn}}"' for mn, _ in measures)
        cols = '"date_key"' + (f", {{dim_cols}}" if dim_cols else "") + (f", {{meas_cols}}" if meas_cols else "")
        sel  = f'TO_CHAR(s."{{date_col}}"::date, \\'YYYYMMDD\\')::INT AS "date_key"'
        if dim_select:
            sel += f", {{dim_select}}"
        if m_csv:
            sel += f", {{m_csv}}"
        with conn.cursor() as c:
            c.execute(
                f'INSERT INTO "{{fact_table}}" ({{cols}}) '
                f'SELECT {{sel}} FROM "{{src_table}}" s'
            )
        conn.commit()


def refresh_views(conn) -> None:
    with conn.cursor() as c:
        c.execute('CALL refresh_olap_all();')
    conn.commit()


def main() -> None:
    conn = _connect()
    try:
        populate_dim_date(conn)
        load_dimensions(conn)
        load_facts(conn)
        refresh_views(conn)
        log.info("OLTP → OLAP ETL complete.")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
'''


# ----------------------------------------------------------------------------
# Script 3 — pytest validation
# ----------------------------------------------------------------------------
_TEST_MIGRATION_TEMPLATE = '''"""test_migration.py — generated by LAMA (iter-13.44, deterministic).

pytest validation for the OLTP migration:
    1. Row-count parity per table (source vs target).
    2. Foreign-key integrity (no dangling target FKs).
    3. Sum-of-measure reconciliation (OLTP totals vs OLAP fact totals).
    4. dim_date covers the full date range of the largest fact.
"""
from __future__ import annotations

import os
import pytest
import psycopg2


def _src():
    import pymysql
    return pymysql.connect(
        host=os.environ["SOURCE_DB_HOST"],
        port=int(os.environ.get("SOURCE_DB_PORT", "3306")),
        user=os.environ["SOURCE_DB_USER"],
        password=os.environ["SOURCE_DB_PASSWORD"],
        database=os.environ["SOURCE_DB_NAME"],
    )


def _tgt():
    return psycopg2.connect(
        host=os.environ["TARGET_DB_HOST"],
        port=int(os.environ.get("TARGET_DB_PORT", "5432")),
        user=os.environ["TARGET_DB_USER"],
        password=os.environ["TARGET_DB_PASSWORD"],
        dbname=os.environ["TARGET_DB_NAME"],
    )


TABLE_PARITY = {parity_literal}

FK_CHECKS = {fk_checks_literal}

MEASURE_RECONCILIATIONS = {reconciliations_literal}


@pytest.mark.parametrize("legacy_table,target_table", TABLE_PARITY)
def test_row_count_parity(legacy_table, target_table):
    s, t = _src(), _tgt()
    try:
        with s.cursor() as sc:
            sc.execute(f"SELECT COUNT(*) FROM `{{legacy_table}}`")
            src_count = sc.fetchone()[0]
        with t.cursor() as tc:
            tc.execute(f'SELECT COUNT(*) FROM "{{target_table}}"')
            tgt_count = tc.fetchone()[0]
        assert tgt_count == src_count, (
            f"Row-count drift {{legacy_table}}={{src_count}} vs {{target_table}}={{tgt_count}}"
        )
    finally:
        s.close()
        t.close()


@pytest.mark.parametrize("target_table,fk_col,ref_table", FK_CHECKS)
def test_fk_integrity(target_table, fk_col, ref_table):
    conn = _tgt()
    try:
        with conn.cursor() as c:
            c.execute(
                f'SELECT COUNT(*) FROM "{{target_table}}" t '
                f'WHERE t."{{fk_col}}" IS NOT NULL '
                f'AND NOT EXISTS (SELECT 1 FROM "{{ref_table}}" r WHERE r."id" = t."{{fk_col}}")'
            )
            dangling = c.fetchone()[0]
            assert dangling == 0, (
                f"{{target_table}}.{{fk_col}} has {{dangling}} dangling refs to {{ref_table}}"
            )
    finally:
        conn.close()


@pytest.mark.parametrize("oltp_table,oltp_measure,fact_table,fact_measure", MEASURE_RECONCILIATIONS)
def test_measure_reconciliation(oltp_table, oltp_measure, fact_table, fact_measure):
    conn = _tgt()
    try:
        with conn.cursor() as c:
            c.execute(f'SELECT COALESCE(SUM("{{oltp_measure}}"), 0) FROM "{{oltp_table}}"')
            src_sum = c.fetchone()[0] or 0
            c.execute(f'SELECT COALESCE(SUM("{{fact_measure}}"), 0) FROM "{{fact_table}}"')
            tgt_sum = c.fetchone()[0] or 0
            assert abs(float(src_sum) - float(tgt_sum)) < 0.01, (
                f"Measure drift {{oltp_table}}.{{oltp_measure}}={{src_sum}} "
                f"vs {{fact_table}}.{{fact_measure}}={{tgt_sum}}"
            )
    finally:
        conn.close()
'''


# ----------------------------------------------------------------------------
# Public API
# ----------------------------------------------------------------------------
def _build_tables_literal(entities: List[dict]) -> str:
    rows: List[str] = []
    for ent in entities:
        if (ent.get("type") or "").upper() != "TABLE":
            continue
        tname = _sanitise(ent.get("name") or "")
        if not tname:
            continue
        cols = []
        fk_map = {(_sanitise(f.get("column") or "")): _sanitise(f.get("ref_table") or "")
                  for f in (ent.get("fks") or [])}
        for c in ent.get("columns") or []:
            cn = _sanitise(c.get("name") or "")
            if not cn or cn == "id":
                continue
            ref = fk_map.get(cn, "")
            is_fk = bool(ref)
            cols.append((cn, cn, is_fk, ref))
        rows.append((tname, tname, cols))
    return repr(rows)


def _build_dim_facts_literals(bus_matrix: Dict[str, Any]) -> tuple[str, str]:
    """Return (dims_literal, facts_literal) for the OLTP→OLAP script."""
    dims_payload: List[tuple] = []
    for d in (bus_matrix.get("dimensions") or []):
        dim_table = _sanitise(d.get("name") or "")
        if not dim_table.startswith("dim_"):
            dim_table = "dim_" + dim_table
        src_table = (d.get("source_tables") or [""])[0]
        if not src_table:
            continue
        natural = (d.get("natural_key") or "id")
        attrs = [(_sanitise(a.get("name") or ""), _sanitise(a.get("source_column") or a.get("name") or ""))
                 for a in (d.get("attributes") or []) if a.get("name")]
        dims_payload.append((dim_table, src_table, natural, attrs))

    facts_payload: List[tuple] = []
    matrix = bus_matrix.get("matrix") or {}
    for f in (bus_matrix.get("facts") or []):
        fact_table = _sanitise(f.get("name") or "")
        if not fact_table.startswith("fact_"):
            fact_table = "fact_" + fact_table
        src_table = (f.get("source_tables") or [""])[0]
        if not src_table:
            continue
        date_col = f.get("date_column") or "created_at"
        # Dim joins from matrix row
        row = matrix.get(f.get("name")) or {}
        dim_joins: List[tuple] = []
        for dim_name, used in row.items():
            if not used or dim_name == "dim_date":
                continue
            dim_key = _sanitise(dim_name if dim_name.startswith("dim_") else f"dim_{dim_name}")
            join_col = dim_key.replace("dim_", "") + "_id"
            dim_joins.append((dim_key, dim_key, "natural_key", join_col))
        measures = [(_sanitise(m.get("name") or ""), _sanitise(m.get("source_column") or m.get("name") or ""))
                    for m in (f.get("measures") or []) if m.get("name")]
        facts_payload.append((fact_table, src_table, date_col, dim_joins, measures))

    return repr(dims_payload), repr(facts_payload)


def _build_test_literals(
    entities: List[dict],
    bus_matrix: Dict[str, Any],
) -> tuple[str, str, str]:
    parity: List[tuple] = []
    fk_checks: List[tuple] = []
    for ent in entities:
        if (ent.get("type") or "").upper() != "TABLE":
            continue
        tname = _sanitise(ent.get("name") or "")
        if not tname:
            continue
        parity.append((tname, tname))
        for fk in (ent.get("fks") or []):
            col = _sanitise(fk.get("column") or "")
            ref = _sanitise(fk.get("ref_table") or "")
            if col and ref:
                fk_checks.append((tname, col, ref))

    reconciliations: List[tuple] = []
    for f in (bus_matrix.get("facts") or []):
        fact_table = _sanitise(f.get("name") or "")
        if not fact_table.startswith("fact_"):
            fact_table = "fact_" + fact_table
        src_table = (f.get("source_tables") or [""])[0]
        if not src_table:
            continue
        for m in (f.get("measures") or []):
            mname = _sanitise(m.get("name") or "")
            scol  = _sanitise(m.get("source_column") or m.get("name") or "")
            if mname and scol:
                reconciliations.append((src_table, scol, fact_table, mname))

    return repr(parity), repr(fk_checks), repr(reconciliations)


def generate_old_to_oltp(entities: List[dict], source_tech: str = "MySQL") -> str:
    return _OLD_TO_OLTP_TEMPLATE.format(
        source_tech=source_tech,
        tables_literal=_build_tables_literal(entities),
    )


def generate_oltp_to_olap(bus_matrix: Dict[str, Any]) -> str:
    dims_lit, facts_lit = _build_dim_facts_literals(bus_matrix)
    return _OLTP_TO_OLAP_TEMPLATE.format(
        dims_literal=dims_lit,
        facts_literal=facts_lit,
    )


def generate_test_migration(
    entities: List[dict],
    bus_matrix: Dict[str, Any],
) -> str:
    parity_lit, fk_lit, recon_lit = _build_test_literals(entities, bus_matrix)
    return _TEST_MIGRATION_TEMPLATE.format(
        parity_literal=parity_lit,
        fk_checks_literal=fk_lit,
        reconciliations_literal=recon_lit,
    )


def generate_all(
    entities: List[dict],
    bus_matrix: Dict[str, Any],
    source_tech: str = "MySQL",
) -> Dict[str, str]:
    """Convenience: return all 3 scripts keyed by artifact type."""
    return {
        "migrate_old_to_oltp":  generate_old_to_oltp(entities, source_tech),
        "migrate_oltp_to_olap": generate_oltp_to_olap(bus_matrix),
        "test_migration":       generate_test_migration(entities, bus_matrix),
    }

