"""Generate Spring Boot @SpringBootApplication entrypoint + Security stub.

Helidon MP boots via `Main` class calling `Server.builder().build().start()`.
Spring Boot needs an `@SpringBootApplication` class. If the source project
has one, we adapt it; otherwise we synthesise one.
"""
from __future__ import annotations
from pathlib import Path


_APP_TEMPLATE = """package {pkg};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Generated by DCTE (Helidon MP -> Spring Boot 3).
 *
 * Original entrypoint (io.helidon.microprofile.server.Main) does not
 * survive the migration. Boot the app with `mvn spring-boot:run` or
 * `java -jar target/*.jar`.
 */
@SpringBootApplication
public class Application {{
    public static void main(String[] args) {{
        SpringApplication.run(Application.class, args);
    }}
}}
"""

_SECURITY_TEMPLATE = """package {pkg};

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.web.SecurityFilterChain;

/**
 * Generated by DCTE. Replaces Helidon Security (JWT/Basic/OIDC) with a
 * Spring Security stub. Wire up your JWT/OAuth2 provider on this bean.
 */
@Configuration
public class SecurityConfig {{
    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {{
        http
            .csrf(csrf -> csrf.disable())
            .authorizeHttpRequests(auth -> auth
                .requestMatchers("/actuator/**", "/v3/api-docs/**", "/swagger-ui/**").permitAll()
                .anyRequest().authenticated()
            )
            .httpBasic(basic -> {{ }});
        return http.build();
    }}
}}
"""


def write_application_class(dest_root: Path, base_pkg: str) -> Path:
    pkg_path = dest_root / "src" / "main" / "java" / Path(*base_pkg.split("."))
    pkg_path.mkdir(parents=True, exist_ok=True)
    out = pkg_path / "Application.java"
    out.write_text(_APP_TEMPLATE.format(pkg=base_pkg), encoding="utf-8")
    return out


def write_security_config(dest_root: Path, base_pkg: str) -> Path:
    pkg_path = dest_root / "src" / "main" / "java" / Path(*base_pkg.split("."))
    pkg_path.mkdir(parents=True, exist_ok=True)
    out = pkg_path / "SecurityConfig.java"
    out.write_text(_SECURITY_TEMPLATE.format(pkg=base_pkg), encoding="utf-8")
    return out


# iter-18.5 — Emit an OpenAPI (Swagger) configuration so springdoc surfaces
# a browsable UI at /swagger-ui.html without further wiring.
_OPENAPI_TEMPLATE = """package {pkg};

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.Contact;
import org.springframework.context.annotation.Configuration;

/**
 * Generated by DCTE. Replaces Helidon OpenAPI with springdoc-openapi.
 * Swagger UI: http://localhost:8080/swagger-ui.html
 * OpenAPI JSON: http://localhost:8080/v3/api-docs
 */
@Configuration
@OpenAPIDefinition(
    info = @Info(
        title = "{title}",
        version = "1.0.0",
        description = "Auto-migrated from Helidon by LAMA DCTE.",
        contact = @Contact(name = "Platform Team")
    )
)
public class OpenApiConfig {{
}}
"""


def write_openapi_config(dest_root: Path, base_pkg: str, title: str = "API") -> Path:
    pkg_path = dest_root / "src" / "main" / "java" / Path(*base_pkg.split("."))
    pkg_path.mkdir(parents=True, exist_ok=True)
    out = pkg_path / "OpenApiConfig.java"
    out.write_text(_OPENAPI_TEMPLATE.format(pkg=base_pkg, title=title), encoding="utf-8")
    return out
