"""Translate microprofile-config.properties → Spring application.properties.

MP config keys are largely compatible; a few well-known ones move.
"""
from __future__ import annotations
from pathlib import Path

from .mappings import MP_CONFIG_KEY_MAP


HEADER = (
    "# Generated by DCTE (Helidon MP -> Spring Boot).\n"
    "# Source: microprofile-config.properties.\n"
)


def translate(source: Path, dest: Path) -> tuple[int, int]:
    """Return `(lines_read, lines_rewritten)`."""
    lines_out: list[str] = [HEADER]
    total = 0
    rewritten = 0
    for raw in source.read_text(encoding="utf-8", errors="ignore").splitlines():
        total += 1
        line = raw.rstrip()
        if not line or line.startswith("#"):
            lines_out.append(line)
            continue
        if "=" not in line:
            lines_out.append(line)
            continue
        key, val = line.split("=", 1)
        key = key.strip()
        val = val.strip()
        new_key = MP_CONFIG_KEY_MAP.get(key, key)
        if new_key != key:
            rewritten += 1
        lines_out.append(f"{new_key}={val}")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines_out) + "\n", encoding="utf-8")
    return total, rewritten
